spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: example-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.kondoumh.kafkaconsumerexample.ExampleEvent
