spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:3001}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
